import mongoose from "mongoose";

const subscriptionSchema = new mongoose.Schema(
	{
		userId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
			index: true,
		},
		planId: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "Plan",
			required: true,
		},

		paypalPlanId: {
			type: String,
			required: true,
		},
		paypalSubscriptionId: {
			type: String,
			required: true,
			unique: true,
		},
		paypalSubscriberId: {
			type: String, // Captures the exact PayPal account ID of the buyer (useful for refunds/support)
		},

		status: {
			type: String,
			// 🔄 UPDATED ENUM TO MATCH YOUR PREVIOUS PAYPAL WEBHOOK CONTROLLER
			enum: [
				"APPROVAL_PENDING", // Generated by backend, waiting for user to log into PayPal
				"APPROVED", // User approved it on PayPal, waiting for PayPal to process the first charge
				"active", // Successfully charging
				"past_due", // Payment failed (PayPal will auto-retry based on your dashboard settings)
				"canceled", // Cancelled by user or admin
				"expired", // Reached the end of its billing cycles
			],
			required: true,
			default: "APPROVAL_PENDING",
		},

		currentPeriodEnd: {
			type: Date,
		},
		cancelAtPeriodEnd: {
			type: Boolean,
			default: false,
		},
	},
	{ timestamps: true }
);

// This helper is perfect exactly as it is!
subscriptionSchema.methods.isValid = function () {
	return (
		this.status === "active" && new Date(this.currentPeriodEnd) > new Date()
	);
};

const Subscription = mongoose.model("Subscription", subscriptionSchema);
export default Subscription;
